### ISSUE TITLE
Error when using the example code given.

### ISSUE THREAD

**Issue by cooperaj** [aequasi/discord-bot-base#2]
When using the example code in the readme I get the error 

``` /Users/name/Projects/Resources/felchbot-discord/node_modules/discord-bot-base/src/Bot.js:6
class Bot {
^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/ulzac/Projects/Resources/felchbot-discord/node_modules/discord-bot-base/src/index.js:53:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I'm using node v5.8.0

**Comment by cryptiklemur** [comment]
Try running on discord-bot-base v4.0.5. Version 5 has a bunch of undocumented changes. I need to document those
